"""Phase 21: analyses that motivate prior-contrastive decoding, from existing runs.

M1. The leak grows as evidence shrinks: share of intervals starting in the first 5% of the window although the
    evidence starts later ("leak"), per memory (no video → unpruned) and per number of sampled frames in the evidence.
M2. The gain comes from where the baseline leaked: per memory, the mIoU change of the final method on questions whose
    baseline interval leaked vs the others, and the share of the total gain contributed by the leaked ones.
M3. Agreeing with the prior signals an error: in the greedy decode trace (random 10%), the first time value written,
    grouped by whether it is also the no-video prior's choice and by its log-likelihood ratio log p(t|video) -
    log p(t|no video); IoU of the resulting answer per group.
Writes logs/phase21/motivation.md. Run from the repo root: python3 logs/phase21/motivation.py
"""
import collections
import glob
import json
import statistics as st
import sys

sys.path.insert(0, "logs/phase15")
sys.path.insert(0, "logs/phase18")
sys.path.insert(0, "logs/phase20")
sys.path.insert(0, "logs/phase21")
from diagnose_gpu import rows_of, run_dir  # noqa: E402
from error_analysis import MEMORIES, cluster_delta, interval  # noqa: E402
from first_time_token import first_step  # noqa: E402
from report import load  # noqa: E402


def late(r):
    return r["_gs"] >= 0.05 * r["_qt"]


def leaked(r):
    iv = interval(r)
    return iv is not None and iv[0] < 0.05 * r["_qt"]


def pct(xs):
    xs = list(xs)
    return 100.0 * sum(xs) / max(len(xs), 1)


def frames_in_evidence(r):
    return 64 * (r["_ge"] - r["_gs"]) / max(r["_qt"], 1e-6)


def main():
    out = ["# Why prior-contrastive decoding: motivating analyses", "",
           "Generated by `logs/phase21/motivation.py` from existing runs (475 questions per memory). "
           "Leak = interval starts in the first 5% of the window although the gold evidence starts later.", ""]

    # M1: leak per memory, and per evidence coverage.
    blind = rows_of("dx-blind-timeline")
    out += ["## M1. The leak grows as evidence shrinks", "",
            "| Memory | Leak, baseline | Leak, PCD | Leak, final |", "|---|---|---|---|",
            f"| no video | {pct(leaked(r) for r in blind.values() if late(r)):.1f}% | — | — |"]
    pcd_tags = {"Random 5%": "random5-cd-blind-a0.5-timeline", "Random 10%": "random10-cd-blind-a0.5-timeline",
                "Random 25%": "random25-cd-blind-a0.5-timeline", "Unpruned": "unpruned-cd-blind-a0.5-timeline",
                "HERMES 10%": "hermes10-cd-blind-a0.5-timeline", "Stratified 10%": "stratified10-cd-blind-a0.5-timeline"}
    runs = {}
    for name, btag, ftag in MEMORIES:
        b, f = load(btag), load(ftag)
        p = load(pcd_tags[name]) if name in pcd_tags else None
        runs[name] = (b, f)
        out.append(f"| {name} | {pct(leaked(r) for r in b.values() if late(r)):.1f}% | "
                   f"{'—' if p is None else f'{pct(leaked(r) for r in p.values() if late(r)):.1f}%'} | "
                   f"{pct(leaked(r) for r in f.values() if late(r)):.1f}% |")
    out.append("")
    bins = [("< 4 frames", 0, 4), ("4–15 frames", 4, 16), ("≥ 16 frames", 16, 1e9)]
    out += ["Leak by the number of the 64 sampled frames inside the evidence (offline memories pooled):", "",
            "| Frames in evidence | Leak, baseline | Leak, final | Leak, no video |", "|---|---|---|---|"]
    offline = [n for n in runs if not n.startswith("Streaming")]
    for label, lo, hi in bins:
        sel = lambda r: late(r) and lo <= frames_in_evidence(r) < hi
        bl = [leaked(r) for n in offline for r in runs[n][0].values() if sel(r)]
        fl = [leaked(r) for n in offline for r in runs[n][1].values() if sel(r)]
        nl = [leaked(r) for r in blind.values() if sel(r)]
        out.append(f"| {label} | {pct(bl):.1f}% | {pct(fl):.1f}% | {pct(nl):.1f}% |")
    out.append("")

    # M2: where the gain comes from.
    out += ["## M2. The gain comes from the questions where the baseline leaked", "",
            "| Memory | Baseline leaked: share of questions | ΔmIoU there | ΔmIoU elsewhere | Share of the total gain |",
            "|---|---|---|---|---|"]
    pooled_leak, pooled_rest = [], []
    for name, (b, f) in runs.items():
        qs = sorted(set(b) & set(f))
        lk = [q for q in qs if late(b[q]) and leaked(b[q])]
        rest = [q for q in qs if q not in set(lk)]
        d = lambda sub: sum(f[q]["_iou"] - b[q]["_iou"] for q in sub)
        total = d(qs)
        pooled_leak += [(q, b[q], f[q]) for q in lk]
        pooled_rest += [(q, b[q], f[q]) for q in rest]
        out.append(f"| {name} | {100 * len(lk) / len(qs):.1f}% | {100 * d(lk) / max(len(lk), 1):+.1f} | "
                   f"{100 * d(rest) / max(len(rest), 1):+.1f} | {100 * d(lk) / total:.0f}% |")
    out += ["", f"Pooled over the 8 memories: ΔmIoU {cluster_delta(pooled_leak, lambda r: 100 * r['_iou'])} on leaked "
            f"questions vs {cluster_delta(pooled_rest, lambda r: 100 * r['_iou'])} elsewhere.", ""]

    # M3: prior agreement in the decode trace.
    tag = "random10-cd-blind-against0.0-timeline"  # greedy decoding with both distributions logged
    rows = rows_of(tag)
    groups = collections.defaultdict(list)
    llr = []
    for path in glob.glob(f"{run_dir(tag)}/cdtrace-*.jsonl"):
        for line in open(path):
            d = json.loads(line)
            s = first_step(d["steps"])
            r = rows.get(d["question_id"])
            if s is None or r is None:
                continue
            top = s["top"]
            chosen = next((t for t in top if t[0] == s["chosen"]), top[0])
            prior_top = max(top, key=lambda t: t[2])
            agree = prior_top[0] == chosen[0]
            groups["agrees with the prior's choice" if agree else "differs from the prior's choice"].append(r["_iou"])
            llr.append((chosen[1] - chosen[2], r["_iou"], r))
    out += ["## M3. Writing what the prior would write signals an error", "",
            f"Greedy decoding at random 10% (`{tag}`), first time value of each answer.", "",
            "| First time value | Questions | mIoU | IoU ≥ 0.5 |", "|---|---|---|---|"]
    for g, ious in sorted(groups.items()):
        out.append(f"| {g} | {len(ious)} | {100 * st.mean(ious):.1f} | {pct(i >= 0.5 for i in ious):.1f}% |")
    llr.sort(key=lambda x: x[0])
    k = len(llr) // 4
    out += ["", "| log p(t | video) − log p(t | no video) of the first time value | Questions | mIoU | Leak |",
            "|---|---|---|---|"]
    for i, label in enumerate(["lowest quarter (prior explains it)", "second", "third", "highest quarter (video explains it)"]):
        part = llr[i * k:(i + 1) * k] if i < 3 else llr[3 * k:]
        out.append(f"| {label} (≤ {part[-1][0]:+.2f}) | {len(part)} | {100 * st.mean(x[1] for x in part):.1f} | "
                   f"{pct(leaked(x[2]) for x in part if late(x[2])):.1f}% |")
    out.append("")
    open("logs/phase21/motivation.md", "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
