"""Phase 21: how token pruning connects to the prior leak and to PCD's gain.

Uses the per-frame retention snapshots of diagnostic runs (tokens encoded and kept per frame, per question; official
prompt) as the record of what each selector removes. HERMES and stratified pruning do not read the real question
(HERMES scores tokens with its own probe questions), so the same tokens survive in the timeline runs of the same
selector and budget; answers are taken from those timeline runs (baseline and final method).

P1. Where in the window each selector keeps tokens (share of encoded tokens kept, by position in the window).
P2. Per question: share of the gold-evidence tokens that survive, and whether any survive; leak and mIoU of the
    baseline and the final method, and the gain, binned by evidence retention.
Writes logs/phase21/pruning_link.md. Run from the repo root: python3 logs/phase21/pruning_link.py
"""
import collections
import glob
import json
import statistics as st
import sys

sys.path.insert(0, "logs/phase15")
sys.path.insert(0, "logs/phase21")
from diagnose_gpu import rows_of, run_dir  # noqa: E402
from error_analysis import cluster_delta  # noqa: E402
from motivation import late, leaked, pct  # noqa: E402

F = "cd-blind-adapt1.0-scopetime-timeline"
SELECTORS = [  # (label, retention run, baseline timeline run, final-method timeline run)
    ("HERMES 10%", "dx-ret-hermes-keep0.1", "offline-hermes-keep0.1-timeline", f"hermes10-{F}"),
    ("Stratified 10%", "dx-ret-stratified-keep0.1", "offline-stratified-keep0.1-timeline", f"stratified10-{F}"),
    ("Random 10%", "dx-ret-random-keep0.1", "offline-random-keep0.1-timeline", f"random10-{F}"),
]


def retention(tag):
    out = {}
    for path in glob.glob(f"{run_dir(tag)}/retention-*.jsonl"):
        for line in open(path):
            s = json.loads(line)
            out[s["question_id"]] = s
    return out


def main():
    out = ["# Token pruning, the prior leak and PCD", "",
           "Generated by `logs/phase21/pruning_link.py`. Retention (tokens kept per frame) from the diagnostic "
           "`dx-ret-*` runs; answers from the timeline runs with the same selector and budget.", ""]
    data = {}
    for label, rtag, btag, ftag in SELECTORS:
        data[label] = (retention(rtag), rows_of(btag), rows_of(ftag))

    # P1: where tokens survive.
    out += ["## P1. Where each selector keeps tokens", "",
            "Share of encoded visual tokens kept, by position of the frame in the question window.", "",
            "| Selector | first 10% | 10–25% | 25–50% | 50–75% | 75–100% | frames with no token left |",
            "|---|---|---|---|---|---|---|"]
    edges = [0.0, 0.10, 0.25, 0.50, 0.75, 1.0001]
    for label, (ret, _, _) in data.items():
        kept, enc, dead, frames = [0.0] * 5, [0.0] * 5, 0, 0
        for s in ret.values():
            times = s["frame_times"]
            span = max(times[-1], 1e-6)
            k, e = ({int(a): b for a, b in s[key].items()} for key in ("kept", "encoded"))
            for i, t in enumerate(times):
                b = next(j for j in range(5) if edges[j] <= t / span < edges[j + 1])
                kept[b] += k.get(i, 0)
                enc[b] += e.get(i, 0)
                dead += k.get(i, 0) < 1
                frames += 1
        out.append(f"| {label} | " + " | ".join(f"{100 * kept[j] / max(enc[j], 1):.1f}%" for j in range(5))
                   + f" | {100 * dead / max(frames, 1):.0f}% |")
    out.append("")

    # P2: evidence retention per question vs leak and gain.
    bins = [("no evidence token kept", lambda x: x == 0), ("< 5% kept", lambda x: 0 < x < 0.05),
            ("5–15% kept", lambda x: 0.05 <= x < 0.15), ("≥ 15% kept", lambda x: x >= 0.15)]
    out += ["## P2. Evidence retention per question: leak and the gain of the final method", "",
            "Evidence retention = share of the encoded tokens of gold-interval frames that survive pruning. "
            "Leak on questions whose evidence starts after the first 5% of the window.", "",
            "| Selector | Evidence retained | Questions | Leak base → final | mIoU base → final | ΔmIoU |",
            "|---|---|---|---|---|---|"]
    pooled = collections.defaultdict(list)
    for label, (ret, base, final) in data.items():
        groups = collections.defaultdict(list)
        for q, s in ret.items():
            if q not in base or q not in final:
                continue
            r = base[q]
            gold = [i for i, t in enumerate(s["frame_times"]) if r["_gs"] <= t <= r["_ge"]]
            if not gold or len(gold) == len(s["frame_times"]):
                continue
            k = {int(a): b for a, b in s["kept"].items()}
            e = {int(a): b for a, b in s["encoded"].items()}
            share = sum(k.get(i, 0) for i in gold) / max(sum(e.get(i, 0) for i in gold), 1)
            name = next(n for n, f in bins if f(share))
            groups[name].append((q, base[q], final[q]))
            pooled[name].append((q, base[q], final[q]))
        for name, _ in bins:
            ps = groups.get(name, [])
            if len(ps) < 10:
                continue
            b, f = [p[1] for p in ps], [p[2] for p in ps]
            out.append(f"| {label} | {name} | {len(ps)} | {pct(leaked(r) for r in b if late(r)):.0f}% → "
                       f"{pct(leaked(r) for r in f if late(r)):.0f}% | {100 * st.mean(r['_iou'] for r in b):.1f} → "
                       f"{100 * st.mean(r['_iou'] for r in f):.1f} | {cluster_delta(ps, lambda r: 100 * r['_iou'])} |")
    out += ["", "Pooled over the three selectors:", "", "| Evidence retained | Instances | Leak base → final | "
            "mIoU base → final | ΔmIoU |", "|---|---|---|---|---|"]
    for name, _ in bins:
        ps = pooled.get(name, [])
        if not ps:
            continue
        b, f = [p[1] for p in ps], [p[2] for p in ps]
        out.append(f"| {name} | {len(ps)} | {pct(leaked(r) for r in b if late(r)):.0f}% → "
                   f"{pct(leaked(r) for r in f if late(r)):.0f}% | {100 * st.mean(r['_iou'] for r in b):.1f} → "
                   f"{100 * st.mean(r['_iou'] for r in f):.1f} | {cluster_delta(ps, lambda r: 100 * r['_iou'])} |")
    out.append("")
    open("logs/phase21/pruning_link.md", "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
