"""Phase 20: does confidence-adaptive PCD keep the gains of PCD without hurting questions whose evidence starts early?

Groups: early-evidence questions (gold start < 5% of the question time) and the rest. For each group: Acc., mIoU,
GQ@0.5 and the early-start rate (share of predicted intervals starting in the first 5% of the window). For early-evidence
questions a high rate is correct; for the rest it is prior leakage. Paired 95% bootstrap Δ against the baseline and PCD.
Writes logs/phase20/early.md. Run from the repo root: python3 logs/phase20/early.py
"""
import sys

sys.path.insert(0, "logs/phase15")
sys.path.insert(0, "logs/phase18")
from diagnose_gpu import metrics, paired, rows_of  # noqa: E402
from report import S, load  # noqa: E402

SETTINGS = [
    ("Random 10%", "offline-random-keep0.1-timeline", "random10-cd-blind-a0.5-timeline", [
        ("adaptive, α_max 1", "random10-cd-blind-adapt1.0-timeline"),
        ("adaptive, α_max 2", "random10-cd-blind-adapt2.0-timeline"),
        ("adaptive, α_max 1, time scope", "random10-cd-blind-adapt1.0-scopetime-timeline"),
        ("time scope", "random10-cd-blind-a0.5-scopetime-timeline"),
        ("evidence-against, α 1", "random10-cd-blind-against1.0-timeline"),
        ("evidence-against, α 2", "random10-cd-blind-against2.0-timeline")]),
    ("Random 25%", "offline-random-keep0.25-timeline", "random25-cd-blind-a0.5-timeline", [
        ("adaptive, α_max 1", "random25-cd-blind-adapt1.0-timeline"),
        ("adaptive, α_max 2", "random25-cd-blind-adapt2.0-timeline"),
        ("time scope", "random25-cd-blind-a0.5-scopetime-timeline"),
        ("adaptive, α_max 1, time scope", "random25-cd-blind-adapt1.0-scopetime-timeline")]),
    ("Unpruned", "timeline", "unpruned-cd-blind-a0.5-timeline", [
        ("adaptive, α_max 1", "unpruned-cd-blind-adapt1.0-timeline"),
        ("adaptive, α_max 2", "unpruned-cd-blind-adapt2.0-timeline"),
        ("adaptive, α_max 1, time scope", "unpruned-cd-blind-adapt1.0-scopetime-timeline"),
        ("time scope", "unpruned-cd-blind-a0.5-scopetime-timeline")]),
    ("Random 5%", "offline-random-keep0.05-timeline", "random5-cd-blind-a0.5-timeline", [
        ("adaptive, α_max 1", "random5-cd-blind-adapt1.0-timeline"),
        ("adaptive, α_max 1, time scope", "random5-cd-blind-adapt1.0-scopetime-timeline")]),
    ("HERMES 10%", "offline-hermes-keep0.1-timeline", "hermes10-cd-blind-a0.5-timeline", [
        ("adaptive, α_max 1", "hermes10-cd-blind-adapt1.0-timeline"),
        ("time scope", "hermes10-cd-blind-a0.5-scopetime-timeline"),
        ("adaptive, α_max 1, time scope", "hermes10-cd-blind-adapt1.0-scopetime-timeline")]),
    ("Stratified 10%", "offline-stratified-keep0.1-timeline", "stratified10-cd-blind-a0.5-timeline", [
        ("adaptive, α_max 1", "stratified10-cd-blind-adapt1.0-timeline"),
        ("adaptive, α_max 1, time scope", "stratified10-cd-blind-adapt1.0-scopetime-timeline")]),
    ("Streaming KV 4k", "@" + S.format(4000, "timeline-"), "@" + S.format(4000, "cd-blind-a0.5-timeline-"), [
        ("adaptive, α_max 1", "@" + S.format(4000, "cd-blind-adapt1.0-timeline-")),
        ("time scope", "@" + S.format(4000, "cd-blind-a0.5-scopetime-timeline-")),
        ("adaptive, α_max 1, time scope", "@" + S.format(4000, "cd-blind-adapt1.0-scopetime-timeline-"))]),
    ("Streaming KV 6k", "@" + S.format(6000, "timeline-"), "@" + S.format(6000, "cd-blind-a0.5-timeline-"), [
        ("adaptive, α_max 1", "@" + S.format(6000, "cd-blind-adapt1.0-timeline-")),
        ("adaptive, α_max 1, time scope", "@" + S.format(6000, "cd-blind-adapt1.0-scopetime-timeline-"))]),
]


def early(r):
    return r["_gs"] < 0.05 * r["_qt"]


def starts_early(rows):
    p = [r for r in rows.values() if r["interval_parseable"]]
    return 100 * sum(min(float(r["pred_start_time"]), float(r["pred_end_time"])) < 0.05 * r["_qt"] for r in p) / max(len(p), 1)


def sub(rows, keep):
    return {q: r for q, r in rows.items() if keep(r)}


def main():
    out = ["# Confidence-adaptive PCD on early-evidence questions", "",
           "Generated by `logs/phase20/early.py`. Early = gold start < 5% of the question time. "
           "Start<5%: share of predicted intervals starting in the first 5% of the window (correct for early questions, "
           "prior leakage for the rest). Δ: paired difference with 95% bootstrap interval vs the baseline (B) and "
           "vs constant-α PCD (P); * = excludes 0.", ""]
    for title, btag, ptag, variants in SETTINGS:
        base, pcd = load(btag), load(ptag)
        if base is None or pcd is None:
            out += [f"## {title}", "", "baseline or PCD pending", ""]
            continue
        out += [f"## {title}", ""]
        for gname, keep in (("all questions", lambda r: True), ("early evidence", early),
                            ("later evidence", lambda r: not early(r))):
            b = sub(base, keep)
            out += [f"### {gname} (n={len(b)})", "",
                    "| Run | Acc. | mIoU | GQ@0.5 | Start<5% | ΔAcc. vs B | ΔmIoU vs B | ΔGQ vs B | ΔAcc. vs P | ΔmIoU vs P | ΔGQ vs P |",
                    "|---|---|---|---|---|---|---|---|---|---|---|"]
            for name, tag in [("baseline", btag), ("PCD α 0.5", ptag)] + [(n, t) for n, t in variants]:
                rows = load(tag)
                if rows is None:
                    out.append(f"| {name} | pending | | | | | | | | | |")
                    continue
                r, p = sub(rows, keep), sub(pcd, keep)
                m = metrics(r)
                vb = [paired(r, b, k) for k in ("acc", "miou", "gq05")] if tag != btag else [""] * 3
                vp = [paired(r, p, k) for k in ("acc", "miou", "gq05")] if tag not in (btag, ptag) else [""] * 3
                out.append(f"| {name} | {m['acc']} | {m['miou']} | {m['gq05']} | {starts_early(r):.1f} | "
                           + " | ".join(vb + vp) + " |")
            out.append("")
        # Discrimination: starting early is only evidence-driven if it happens for early-evidence questions and
        # not for the rest. J = early-start rate (early evidence) - early-start rate (later evidence).
        out += [f"### Early-start discrimination", "", "| Run | early evidence | later evidence (leak) | J |", "|---|---|---|---|"]
        for name, tag in [("no video", "dx-blind-timeline"), ("baseline", btag), ("PCD α 0.5", ptag)] + list(variants):
            rows = load(tag) or (None if tag.startswith("@") else rows_of(tag))
            if rows is None:
                continue
            e, l = starts_early(sub(rows, early)), starts_early(sub(rows, lambda r: not early(r)))
            out.append(f"| {name} | {e:.1f} | {l:.1f} | {e - l:.1f} |")
        out.append("")
    open("logs/phase20/early.md", "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
